[package]
name = "monrst"
version = "0.1.0"
edition = "2021"

authors = [
    "Balthazar Patiachvili"
]
license = "GPL-3.0-or-later"

[dependencies]
rocket = "=0.5.0-rc.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["serde", "v4"] }