all-features = true

[advisories]
notice = "deny"
unmaintained = "deny"
unsound = "deny"
vulnerability = "deny"
yanked = "deny"

[bans]
multiple-versions = "allow"

[licenses]
allow = ["Apache-2.0", "MIT"]
allow-osi-fsf-free = "both"
confidence-threshold = 1
copyleft = "allow"
default = "deny"
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" }
]
unlicensed = "deny"

[sources]
unknown-registry = "deny"
