all-features = true

[advisories]
notice = "deny"
unmaintained = "deny"
unsound = "deny"
vulnerability = "deny"
yanked = "deny"

[licenses]
confidence-threshold = 1
copyleft = "allow"
default = "deny"
unlicensed = "deny"

[sources]
unknown-registry = "deny"
