name: Build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.base_ref }}-build
  cancel-in-progress: true

jobs:

  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialization
        run: cargo install cargo-deny
      - name: Cache restore
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: "target/"
          key: ${{ runner.os }}-cache
      - name: Check
        run: |
          cargo deny check
          cargo fmt --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features --no-deps
      - name: Build
        run: cargo build
      - name: Tests
        run: cargo test
      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v3
        with:
          path: "target/"
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}