name: Build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:

  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialization
        run: cargo install cargo-deny
      - name: Check
        run: |
          cargo deny check
          cargo fmt --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features --no-deps
      - name: Build
        run: cargo build
      - name: Tests
        run: cargo test
