name: Build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.base_ref }}-build
  cancel-in-progress: true

jobs:

  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cargo cache restore
        id: cargo-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            "~/.cargo/git"
            "~/.cargo/registry"
          key: ${{ runner.os }}
      - name: Initialization
        run: cargo install cargo-deny
      - name: Save cargo cache
        id: cargo-cache-save
        uses: actions/cache/save@v3
        with:
          path: |
            "~/.cargo/git"
            "~/.cargo/registry"
          key: ${{ steps.cargo-cache-restore.outputs.cache-primary-key }}
      - name: Target cache restore
        id: target-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            "target/"
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Check
        run: |
          cargo deny check
          cargo fmt --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features --no-deps --workspace
      - name: Build
        run: cargo build
      - name: Save target cache
        id: target-cache-save
        uses: actions/cache/save@v3
        with:
          path: "target/"
          key: ${{ steps.cargo-cache-restore.outputs.cache-primary-key }}
      - name: Tests
        run: cargo test